#!/usr/bin/env python3

import json
import base64
import requests
import os
from crewai_tools import tool
import auth

# --- Configuration for Stable Diffusion ---
# !! IMPORTANT: Replace with the actual IP/hostname of your Automatic1111 server !!
STABLE_DIFFUSION_API_URL = "http://YOUR_KALI_IP_OR_HOSTNAME:7860" # e.g., "http://192.168.1.100:7860"
# ----------------------------------------

# --- Import all v8 tools ---
from fapc_tools_v8 import (
    secure_cli_tool, click_screen_tool, take_screenshot_tool,
    analyze_screenshot_tool, delegate_to_crew, defensive_nmap_tool,
    start_browser_tool, stop_browser_tool, navigate_url_tool,
    fill_form_tool, click_element_tool, read_page_text_tool,
    add_secure_credential_tool, get_secure_credential_tool,
    notify_human_for_help_tool
)
_ = (secure_cli_tool, click_screen_tool, take_screenshot_tool,
     analyze_screenshot_tool, delegate_to_crew, defensive_nmap_tool,
     start_browser_tool, stop_browser_tool, navigate_url_tool,
     fill_form_tool, click_element_tool, read_page_text_tool,
     add_secure_credential_tool, get_secure_credential_tool,
     notify_human_for_help_tool)
# ---

# --- NEW TOOL: Stable Diffusion Image Generation ---

@tool("Generate Image Tool")
def generate_image_tool(
    prompt: str,
    output_path: str,
    negative_prompt: str = "",
    steps: int = 20,
    cfg_scale: float = 7.0,
    width: int = 512,
    height: int = 512,
    sampler: str = "Euler a",
    seed: int = -1,
    user_id: int = None
) -> str:
    """
    Generates an image using a local Stable Diffusion API (Automatic1111).
    - prompt: The positive text prompt for the image.
    - output_path: The local path to save the generated image (e.g., 'logo.png').
    - negative_prompt: (Optional) Things to avoid in the image.
    - steps: (Optional) Number of sampling steps (default 20).
    - cfg_scale: (Optional) Classifier Free Guidance scale (default 7.0).
    - width: (Optional) Image width in pixels (default 512).
    - height: (Optional) Image height in pixels (default 512).
    - sampler: (Optional) Sampler method (default 'Euler a').
    - seed: (Optional) The random seed to use (-1 for random).
    - user_id: The user_id for logging.
    """
    print(f"\n[Tool Call: generate_image_tool] PROMPT: '{prompt}'")
    print(f"  - SAVING TO: {output_path}")

    url = f"{STABLE_DIFFUSION_API_URL}/sdapi/v1/txt2img"
    
    payload = {
        "prompt": prompt,
        "negative_prompt": negative_prompt,
        "steps": steps,
        "cfg_scale": cfg_scale,
        "width": width,
        "height": height,
        "sampler_name": sampler,
        "seed": seed,
        "n_iter": 1, # Generate 1 image
        "batch_size": 1,
    }

    try:
        response = requests.post(url, json=payload, timeout=120) # 2-min timeout
        response.raise_for_status() # Raise an exception for bad status codes
        
        r = response.json()
        
        # Images are returned in base64 format
        if not r.get("images"):
            auth.log_activity(user_id, 'generate_image', f"No image returned for '{prompt}'", 'failure')
            return "Error: No image was generated by the API."
        
        image_data = base64.b64decode(r["images"][0])
        
        with open(output_path, 'wb') as f:
            f.write(image_data)
            
        auth.log_activity(user_id, 'generate_image', f"Image '{prompt}' saved to {output_path}", 'success')
        return f"Success: Image generated and saved to {output_path}"
        
    except requests.exceptions.ConnectionError:
        auth.log_activity(user_id, 'generate_image', f"Connection error to SD API at {STABLE_DIFFUSION_API_URL}", 'failure')
        return f"Error: Could not connect to Stable Diffusion API at {STABLE_DIFFUSION_API_URL}. Is it running and accessible?"
    except requests.exceptions.RequestException as e:
        auth.log_activity(user_id, 'generate_image', f"API request error for '{prompt}'", str(e))
        return f"Error with Stable Diffusion API request: {e}"
    except Exception as e:
        auth.log_activity(user_id, 'generate_image', f"Error during image generation for '{prompt}'", str(e))
        return f"Error generating image: {e}"